import json

l = {
    'as': 'Assault',
    'ac': 'Accident',
    'tf': 'Traffic Law',
    'ht': 'Human Trafficking',
    'ar': 'Arson',
    'd': 'Drugs',
    'mi': 'Missing',
    'mu': 'Murder',
    'p': 'Public Nuisance',
    't': 'Theft',
    'r': 'Robbery',
    'g': 'Gun Violence',
    's': 'Sex Crime',
    'f': 'Fraud',
    'o': 'Others',
    'h': 'Harrassment',
    'cc': 'Child Crime',
}
temp = {
    'All Other Larceny': l['t'],
    'Animal Cruelty': l['o'],
    'Arson': l['ar'],
    'Assisting or Promoting Prostitution': l['s'],
    'Bad Checks': l['o'],
    'Betting/Wagering': l['o'],
    'Bribery': l['o'],
    'Counterfeiting/Forgery': l['f'],
    'Credit Card/Automated Teller Machine Fraud': l['f'],
    'Curfew/Loitering/Vagrancy Violations': l['p'],
    'Destruction/Damage/Vandalism of Property': l['p'],
    'Driving Under the Influence': l['tf'],
    'Drug Equipment Violations': l['d'],
    'Drug/Narcotic Violations': l['d'],
    'Drunkenness': l['p'],
    'Embezzlement': l['f'],
    'Extortion/Blackmail': l['h'],
    'False Pretenses/Swindle/Confidence Game': l['f'],
    'Family Offenses, Nonviolent': l['o'],
    'Fondling': l['s'],
    'Hacking/Computer Invasion': l['p'],
    'Human Trafficking, Commercial Sex Acts': l['ht'],
    'Identity Theft': l['f'],
    'Impersonation': l['f'],
    'Incest': l['s'],
    'Justifiable Homicide': l['mu'],
    'Kidnapping/Abduction': l['mi'],
    'Liquor Law Violations': l['p'],
    'Motor Vehicle Theft': l['t'],
    'Murder & Nonnegligent Manslaughter': l['mu'],
    'Operating/Promoting/Assisting Gambling': l['p'],
    'Peeping Tom': l['s'],
    'Pocket-picking': l['t'],
    'Pornography/Obscene Material': l['s'],
    'Prostitution': l['s'],
    'Purchasing Prostitution': l['s'],
    'Purse-snatching': l['s'],
    'Rape': l['s'],
    'Robbery': l['r'],
    'Sexual Assault With An Object': l['s'],
    'Shoplifting': l['t'],
    'Sodomy': l['s'],
    'Statutory Rape': l['s'],
    'Stolen Property Offenses': l['r'],
    'Theft From Building': l['t'],
    'Theft From Coin-Operated Machine or Device': l['t'],
    'Theft From Motor Vehicle': l['t'],
    'Theft of Motor Vehicle Parts or Accessories': l['t'],
    'Weapon Law Violations': l['g'],
    'Welfare Fraud': l['f'],
    'Wire Fraud': l['f'],

}

with open("map.json", "w") as outfile:
    json.dump(temp,outfile)
# print(sorted(temp.items()))